version: '3.7'
### Compose para Soma #######################################

networks:
    db_network:
        external: true
    backend:
      name: ${COMPOSE_NETWORK_NAME}
      driver: bridge
      
services:

### nodejs Container #######################################
  nodejs:
    build: 
      context: ./docker/nodejs
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./:/var/www
    networks:
      - backend
      - db_network

### Redis ################################################
  redis:
    build: ./docker/redis
    volumes:
      - ${DATA_SAVE_PATH}/redis:/data
    networks:
      - backend

### Nginx Server Container ##################################

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ${APPLICATION}:/var/www:cached
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${APP_WEB_PATH}:/var/www/.front-end:cached
    depends_on:
      - nodejs
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - NODE_CONTAINER_NAME=${NODE_CONTAINER_NAME}
    #é a única forma de passar variáveis de ambiente para a conf do nginx, lembre-se de escapar com $$ as variáveis
    command: /bin/bash -c "envsubst '$$SERVER_NAME $$NODE_CONTAINER_NAME' < /etc/nginx/sites-available/.default.conf.template > /etc/nginx/sites-available/default.conf && exec nginx"
    restart: always
    networks:
      - backend
    # keys usadas pelo proxy do traefik pra pode descobrir o endereço da aplicação
    labels:
      - traefik.enable=true
      - traefik.backend=${COMPOSE_PROJECT_NAME}_nginx
      - traefik.frontend.rule=Host:${SERVER_NAME}
      - traefik.docker.network=${COMPOSE_NETWORK_NAME}